gamemanager/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

# fmt: off
urlpatterns = [
    path("", views.home, name="home"),

    path("events/", views.EventListView.as_view(), name="event list"),
    path("events/search/<str:search>/", views.EventFilteredListView.as_view(), name="event filtered list"),
    path("events/create/", views.EventUpdateCreateView.as_view(), name="event create"),
    path("events/<int:pk>/", views.EventDetailView.as_view(), name="event detail"),
    path("events/<int:event_id>/update_status/<int:status_id>/", views.event_update_status, name="event update status"),
    path("events/<int:pk>/delete/", views.EventDeleteView.as_view(), name="event delete"),
    path("events/<int:pk>/qr/", views.EventQRView.as_view(), name="event qr"),
    path("events/<int:pk>/live/", views.event_live, name="event live"),
    path("events/<int:pk>/live/brackets/set", views.event_set_brackets, name="event live set brackets"),
    path("events/<int:pk>/live/brackets/get", views.event_get_brackets, name="event live get brackets"),
    path("events/<int:pk>/live/admin/", views.event_live_admin, name="event live admin"),
    path("events/<int:pk>/live_content/", views.event_live_content, name="event live content"),
    path("events/<int:pk>/live_extrapoints/", views.live_extrapoints, name="event live extrapoints"),
    path("events/<int:pk>/placements/delete/", views.EventPlacementsDelete.as_view(), name="event delete placements"),
    path("events/<int:event_id>/gamewish/", views.event_gamewish, name="event gamewish"),
    path("events/<int:event_id>/gameimportance/", views.event_gameimportance, name="event gameimportance"),
    path("events/<int:pk>/gameimportance2/", views.event_gameimportance_2, name="event gameimportance2"),
    path("events/<int:event_id>/gameimportance/delete/<int:player_id>/", views.EventGameImportanceDelete.as_view(), name="event gameimportance delete"),
    path("events/<int:event_id>/gameimportance2/delete/<int:player_id>/", views.EventGameImportance2Delete.as_view(), name="event gameimportance2 delete"),
    path("events/<int:event_id>/signdown/", views.event_signdown, name="event signdown"),
    path("events/<int:event_id>/signup/", views.event_signup, name="event signup"),
    path("events/<int:pk>/update/", views.EventUpdateCreateView.as_view(), name="event update"),
    path("events/<int:pk>/insert_scores/", views.score_record_insert, name="event insert-score"),
    path("events/<int:pk>/post_summary/", views.EventPostSummary.as_view(), name="event post summary"),

    path("games/", views.GameListView.as_view(), name="game list"),
    path("games/add/", views.GameCreateUpdateView.as_view(), name="game add"),
    path("games/import/steam/", views.GameImportSteamView.as_view(), name="game import steam"),
    path("games/<int:pk>/", views.GameDetailView.as_view(), name="game detail"),
    path("games/<int:pk>/update/", views.GameCreateUpdateView.as_view(), name="game update"),
    path("games/<int:pk>/delete/", views.GameDeleteView.as_view(), name="game delete"),
    path("games/import/steam/", views.GameImportSteamView.as_view(), name="game import steam"),

    path("boardgames/", views.BoardGameListView.as_view(), name="boardgame list"),
    path("boardgames/add/", views.BoardGameCreateUpdateView.as_view(), name="boardgame add"),
    path("boardgames/<int:pk>/", views.BoardGameDetailView.as_view(), name="boardgame detail"),
    path("boardgames/<int:pk>/update/", views.BoardGameCreateUpdateView.as_view(), name="boardgame update"),
    path("boardgames/<int:pk>/delete/", views.BoardGameDeleteView.as_view(), name="boardgame delete"),
    path("boardgames/import/bgg/", views.BoardGameImportBGGView.as_view(), name="boardgame import bgg"),

    path("score/", views.ScoreRecordListView.as_view(), name="score list"),
    path("score/<int:year>/", views.ScoreRecordListView.as_view(), name="score list"),

    path("accounts/", views.PlayerListView.as_view(), name="player list"),
    path("accounts/adminlist", views.PlayerAdminListView.as_view(), name="player list admin"),
    path("accounts/login/", views.CustomLoginView.as_view(), name="login"),
    path("accounts/logout/", views.custom_logout, name="logout"),
    path("accounts/create/", views.player_create, name="player create"),
    path("accounts/<int:pk>/", views.PlayerDetailView.as_view(), name="player detail"),
    path("accounts/<int:pk>/update/", views.PlayerUpdateView.as_view(), name="player update"),
    path("accounts/<int:pk>/delete/", views.PlayerDeleteView.as_view(), name="player delete"),
    path("accounts/<int:pk>/update_password/", views.PlayerUpdatePasswordView.as_view(), name="player update-password"),
    path("accounts/tokens/", views.PlayerTokenListView.as_view(), name="usertoken list"),
    path("accounts/tokens/create/", views.PlayerTokenCreateView.as_view(), name="usertoken create"),
    path("accounts/tokens/<int:pk>/delete/", views.PlayerTokenDeleteView.as_view(), name="usertoken delete"),
    path("accounts/create/<str:token>/", views.player_create, name="user create with token"),

    path("bugs/", views.BugListView.as_view(), name="bugreport list"),
    path("bugs/create/", views.BugCreateUpdateView.as_view(), name="bugreport create"),
    path("bugs/<int:pk>/update/", views.BugCreateUpdateView.as_view(), name="bugreport update"),
    path("bugs/<int:pk>/delete/", views.BugDeleteView.as_view(), name="bugreport delete"),

    path("news/", views.NewsListView.as_view(), name="news list"),
    path("news/<int:pk>/", views.NewsDetailView.as_view(), name="news detail"),
    path("news/create/", views.NewsUpdateCreateView.as_view(), name="news create"),
    path("news/<int:pk>/update/", views.NewsUpdateCreateView.as_view(), name="news update"),
    path("news/<int:pk>/delete/", views.NewsDeleteView.as_view(), name="news delete"),

    path("food/", views.FoodListView.as_view(), name="food list"),
    path("food/<int:pk>/", views.FoodDetailView.as_view(), name="food detail"),
    path("food/create/", views.FoodUpdateCreateView.as_view(), name="food create"),
    path("food/<int:pk>/update/", views.FoodUpdateCreateView.as_view(), name="food update"),
    path("food/<int:pk>/delete/", views.FoodDeleteView.as_view(), name="food delete"),

    path("moneytransactions/create/", views.MoneyTransactionUpdateCreateView.as_view(), name="moneytransactions create"),
    path("moneytransactions/", views.MoneyTransactionListView.as_view(), name="moneytransactions list"),
    path("moneytransactions/<int:pk>/update/", views.MoneyTransactionUpdateCreateView.as_view(), name="moneytransactions update"), 

    path("commits/", views.commit_list_view, name="commit list"),
    
    path("resources/", views.resources, name="resources"),

    path("rate/<str:model_str>/<int:pk>/<str:rating>/", views.rating_view, name="generic rating"),

    path("extrapoints/<int:pk>/delete/", views.extrapoints_delete, name="extrapoints delete"),
]
# fmt: on

lsbfgtmp_d2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    url(r"^comments/", include("django_comments.urls")),
    path("", include("gamemanager.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamemanager/models.py
from django.contrib.auth.models import User, Group
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

import datetime


class Player(models.Model):
    gamertag = models.CharField(max_length=30, blank=False, null=True, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    get_event_notifications = models.BooleanField(
        "Vill ha event-notifikationer", default=False, blank=False
    )
    get_news_notifications = models.BooleanField(
        "Vill ha nyhetsnotifikationer", default=False, blank=False
    )
    image = models.ImageField(upload_to="profiles", null=True, blank=True)
    verified_mail = models.BooleanField("Verifierad mail", default=False, blank=False)

    @property
    def get_photo_url(self):
        if self.image and hasattr(self.image, "url"):
            return self.image.url
        else:
            return "/static/gamemanager/images/default_user_profile.svg"

    def __str__(self):
        return '%s "%s" %s' % (self.user.first_name, self.gamertag, self.user.last_name)

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        if self.user:
            self.user.delete()


class Team(models.Model):
    teamname = models.CharField(max_length=100, blank=False)
    players = models.ManyToManyField(Player, verbose_name="Spelare", blank=False)


class Rating(models.Model):
    ratings = (
        (0, "Inget betyg"),
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (-1, "Vidrigt"),
    )

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    player = models.ForeignKey(
        Player,
        verbose_name="Spelare",
        on_delete=models.CASCADE,
        blank=False,
        null=False,
    )
    rating = models.IntegerField("Betyg", choices=ratings, default=0)

    class Meta:
        unique_together = ("content_type", "object_id", "player")


class Food(models.Model):
    name = models.CharField("Maträtt", max_length=200)
    description = models.TextField("Recept", blank=True, null=True)
    recipe_link = models.URLField("Receptlänk", blank=True, null=True)
    added_by = models.ForeignKey(
        Player,
        verbose_name="Tillagt av",
        on_delete=models.CASCADE,
        blank=False,
        default=0,
    )
    image = models.ImageField(upload_to="food_images", null=True, blank=True)

    class Meta:
        ordering = ["name"]

    @property
    def get_photo_url(self):
        if self.image and hasattr(self.image, "url"):
            return self.image.url
        else:
            return "#"

    def __str__(self):
        return self.name


class PlayerCreateToken(models.Model):
    token = models.CharField(
        max_length=30,
        blank=False,
        default="000000000000000000000000000000",
        unique=True,
    )
    email = models.EmailField(blank=False, null=True, unique=True)
    expire_date = models.DateTimeField(
        blank=False, null=True, default=datetime.datetime(2000, 1, 1)
    )

    class Meta:
        ordering = ["-expire_date"]


class News(models.Model):
    heading = models.CharField("Rubrik", max_length=100, blank=False, null=True)
    article_text = models.TextField("Text", blank=False, null=True)
    date = models.DateTimeField("Datum", auto_now_add=True, blank=False, null=True)
    added_by = models.ForeignKey(
        Player,
        verbose_name="Tillagt av",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    def __str__(self):
        return '"%s"' % (self.heading)

    class Meta:
        ordering = ["-date"]


class Game(models.Model):
    name = models.CharField("Namn", max_length=200)
    system = models.CharField(max_length=100)
    no_of_players = models.IntegerField("Antal spelare", blank=False, null=True)
    boxart = models.ImageField(upload_to="boxarts", null=True, blank=True)
    youtube = models.URLField("Youtube-länk", blank=True, null=True)
    description = models.TextField("Beskrivning", blank=True, null=True)
    added_by = models.ForeignKey(
        Player,
        verbose_name="Tillagt av",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["system", "name"]

    @property
    def get_photo_url(self):
        if self.boxart and hasattr(self.boxart, "url"):
            return self.boxart.url
        else:
            return "/static/gamemanager/images/default_game_icon.png"

    def __str__(self):
        return self.name + " (" + self.system + ")"


class BoardGame(models.Model):
    name = models.CharField("Namn", max_length=200)
    owner = models.ForeignKey(
        Player,
        verbose_name="Ägare",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="owning_player",
    )
    no_of_players = models.IntegerField("Antal spelare", blank=False, null=True)
    boxart = models.ImageField(upload_to="boardgame_boxarts", null=True, blank=True)
    youtube = models.URLField("Youtube-länk", blank=True, null=True)
    description = models.TextField("Beskrivning", blank=True, null=True)
    added_by = models.ForeignKey(
        Player,
        verbose_name="Tillagt av",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    @property
    def get_photo_url(self):
        if self.boxart and hasattr(self.boxart, "url"):
            return self.boxart.url
        else:
            return "/static/gamemanager/images/default_game_icon.png"


class Event(models.Model):
    statuses_choices = (
        (0, "Pending"),
        (1, "Voting"),
        (2, "Playing"),
        (3, "Finished"),
        (4, "Locked"),
    )

    types_choices = (
        (0, "Game tournament"),
        (1, "General"),
        (2, "Board games"),
    )

    class Meta:
        ordering = ["-date"]

    name = models.CharField("Namn", max_length=200)
    status = models.IntegerField(
        "Status", choices=statuses_choices, blank=False, default=0
    )
    type = models.IntegerField("Typ", choices=types_choices, blank=False, default=1)
    location = models.CharField("Plats", max_length=200, blank=True, null=True)
    location_href = models.URLField("Plats-länk", max_length=200, blank=True, null=True)
    info = models.TextField("Extra information", blank=True, null=True)
    date = models.DateTimeField("Datum")
    date_preliminary = models.BooleanField("Preliminärt datum", default=True)
    games = models.ManyToManyField(Game, verbose_name="Spel", blank=True)
    boardgames = models.ManyToManyField(BoardGame, verbose_name="Brädspel", blank=True)
    players = models.ManyToManyField(Player, verbose_name="Spelare", blank=True)
    cannot_attend = models.ManyToManyField(
        Player,
        verbose_name="Spelare som ej kan vara med",
        blank=True,
        related_name="players_noattend",
    )
    hidden_score = models.BooleanField("Dölj poäng", default=True)
    wallpaper = models.ImageField(upload_to="events", blank=True, default="")
    logo = models.ImageField(upload_to="events", blank=True, default="")
    added_by = models.ForeignKey(
        Player,
        verbose_name="Skapare",
        on_delete=models.CASCADE,
        null=True,
        related_name="added_by",
    )
    score = models.IntegerField("Poäng", blank=False, default=1000000)
    thirdplace_factor = models.FloatField(
        "Tredjeplats poängfaktor", blank=False, default=0.1
    )
    secondplace_factor = models.FloatField(
        "Andraplats poängfaktor", blank=False, default=0.3
    )
    firstplace_factor = models.FloatField(
        "Förstaplats poängfaktor", blank=False, default=0.6
    )
    food = models.ManyToManyField(Food, verbose_name="Maträtter", blank=True)
    bracket_data = models.TextField("Bracket data", blank=True, null=True)

    def __str__(self):
        return self.name


# ---


class TournamentEventManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=0)


class TournamentEvent(Event):
    objects = TournamentEventManager()

    class Meta:
        proxy = True


class GeneralEventManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=1)


class GeneralEvent(Event):
    objects = GeneralEventManager()

    class Meta:
        proxy = True


class BoardGameEventManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=2)


class BoardGameEvent(Event):
    objects = BoardGameEventManager()

    class Meta:
        proxy = True


# ---


class GameWish(models.Model):
    rating_choices = (
        (-1, "Veto"),
        (0, "No"),
        (1, "Yes"),
        (2, "Favourite"),
    )

    game = models.ForeignKey(Game, on_delete=models.CASCADE, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    player = models.ForeignKey(Player, on_delete=models.CASCADE, null=True)
    rating = models.IntegerField(choices=rating_choices, null=True)

    class Meta:
        unique_together = ("event", "player", "game")


class ImportanceRating(models.Model):
    importance_choices = (
        (0, "Less"),
        (1, "Same"),
        (2, "More"),
    )

    game1 = models.ForeignKey(
        Game,
        verbose_name="Spel 1",
        on_delete=models.CASCADE,
        blank=False,
        null=True,
        related_name="game1",
    )
    game2 = models.ForeignKey(
        Game,
        verbose_name="Spel 2",
        on_delete=models.CASCADE,
        blank=False,
        null=True,

gamemanager/templates/gamemanager/clearable_file_input.html
<div id="custom_image_field">
	{% if widget.is_initial %}
		<img src="{{ widget.value.url }}">
	{% endif %}	

	<div class="file">
		<label class="browse_label" for="{{ widget.name }}">
		{% if widget.is_initial %}
			Byt bild
		{% else %}	
			Ny bild
		{% endif %}	
		</label>
		<input type="{{ widget.type }}" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>
	</div>

	<div class="delete">
	{% if widget.is_initial and not widget.required%}
		<label class="checkbox_label" for="{{ widget.checkbox_id }}">{{ widget.clear_checkbox_label }}</label>
		<input id="imagefield_checkbox" type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}">
	{% endif %}	
	</div>

</div>

gamemanager/templates/gamemanager/html_mail_template.html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Simple Transactional Email</title>
    <style>
			/* -------------------------------------
			GLOBAL RESETS
			------------------------------------- */
			.header {
			background-color:#3276b1;
			padding:10px
			}
			.header h1 {
			border-radius: 0.2em;
			padding: 16px 30px 8px 30px;
			width: 7em;
			background: #333C44;
			text-shadow: 1px 1px 1px #34495e;
			text-align: center;
			order: 1;
			margin: 0;
			margin-right: 0.5em;
			}
			.header h1 a{
			font-family: 'Raleway', sans-serif !important;
			font-size: 1.2em;
			font-weight:700 !important;"
			display: block;
			line-height: 0.2;
			text-decoration: none;
			color: #ffffff !important;
			}
			.header p {
			order: 2;
			font-size: 14px;
			margin: 0.5em 0 0 0.5em;
			color: white;
			}
			a.btn2 {
			background-color: #3276b1 !important;
			background-image: none;
			border-bottom-left-radius: 6px;
			border-bottom-right-radius: 6px;
			border-top-left-radius: 6px;
			border-top-right-radius: 6px;
			color: rgb(255, 255, 255);
			display: block;
			font-family: "raleway", verdana;
			font-size: 18px;
			margin-bottom: 9px;
			margin-left: 9px;
			margin-right: 9px;
			margin-top: 9px;
			padding-bottom: 10px;
			padding-left: 0px;
			padding-right: 0px;
			padding-top: 10px;
			text-align: center;
			text-decoration-color: rgb(255, 255, 255);
			text-decoration-line: none;
			text-decoration-style: solid;
			text-decoration-thickness: auto;
			user-select: none;
			vertical-align: middle;
			white-space: nowrap;
			width: 275.217px;
			}
			.table {
			width: 100%;
			margin-bottom: 1rem;
			color: #212529;
			box-shadow: rgba(0, 0, 0, 0.5) 0px 0px 1.6px 0px;
			margin-top: 30px;
			border-collapse: collapse;
			}
			.table tr th:first-child {
			text-align: right;
			width: 100px;
			border-right: 0.4em solid #3276B1;
			}
			.table th,
			.table td {
			padding: 0.75rem;
			vertical-align: top;
			border-top: 1px solid #dee2e6;
			}
			.table thead th {
			vertical-align: bottom;
			border-bottom: 2px solid #dee2e6;
			}
			.table tbody + tbody {
			border-top: 2px solid #dee2e6;
			}
			.table-striped tbody tr:nth-of-type(odd) {
			background-color: rgba(0, 0, 0, 0.05);
			}
			/*All the styling goes here*/
			img {
			border: none;
			-ms-interpolation-mode: bicubic;
			max-width: 100%; 
			}
			body {
			background-color: #f6f6f6;
			font-family: sans-serif;
			-webkit-font-smoothing: antialiased;
			font-size: 14px;
			line-height: 1.4;
			margin: 0;
			padding: 0;
			-ms-text-size-adjust: 100%;
			-webkit-text-size-adjust: 100%; 
			}
			table {
			border-collapse: separate;
			mso-table-lspace: 0pt;
			mso-table-rspace: 0pt;
			width: 100%; }
			table td {
			font-family: sans-serif;
			font-size: 14px;
			vertical-align: top; 
			}
			/* -------------------------------------
			BODY & CONTAINER
			------------------------------------- */
			.body {
			background-color: #f6f6f6;
			width: 100%; 
			}
			/* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
			.container {
			display: block;
			margin: 0 auto !important;
			/* makes it centered */
			max-width: 580px;
			padding: 10px;
			width: 580px; 
			}
			/* This should also be a block element, so that it will fill 100% of the .container */
			.content {
			box-sizing: border-box;
			display: block;
			margin: 0 auto;
			max-width: 580px;
			padding: 10px; 
			}
			/* -------------------------------------
			HEADER, FOOTER, MAIN
			------------------------------------- */
			.main {
			background: #ffffff;
			border-radius: 3px;
			width: 100%; 
			}
			.wrapper {
			box-sizing: border-box;
			padding: 20px; 
			}
			.content-block {
			padding-bottom: 10px;
			padding-top: 10px;
			}
			.footer {
			clear: both;
			margin-top: 10px;
			text-align: center;
			width: 100%; 
			}
			.footer td,
			.footer p,
			.footer span,
			.footer a {
			color: #999999;
			font-size: 12px;
			text-align: center; 
			}
			/* -------------------------------------
			TYPOGRAPHY
			------------------------------------- */
			h1,
			h2,
			h3,
			h4 {
			color: #000000;
			font-family: 'Raleway', sans-serif !important;
			font-weight: 400;
			line-height: 1.4;
			margin: 0;
			margin-bottom: 30px; 
			}
			h1 {
			font-size: 35px;
			font-weight: 300;
			text-align: center;
			text-transform: capitalize; 
			}
			p,
			ul,
			ol {
			font-family: 'Raleway', sans-serif !important;
			font-size: 14px;
			font-weight: normal;
			margin: 0;
			margin-bottom: 15px; 
			line-height: 160%
			}
			p li,
			ul li,
			ol li {
			list-style-position: inside;
			margin-left: 5px; 
			}
			a {
			color: #3498db;
			text-decoration: underline; 
			}
			/* -------------------------------------
			OTHER STYLES THAT MIGHT BE USEFUL
			------------------------------------- */
			.last {
			margin-bottom: 0; 
			}
			.first {
			margin-top: 0; 
			}
			.align-center {
			text-align: center; 
			}
			.align-right {
			text-align: right; 
			}
			.align-left {
			text-align: left; 
			}
			.clear {
			clear: both; 
			}
			.mt0 {
			margin-top: 0; 
			}
			.mb0 {
			margin-bottom: 0; 
			}
			.preheader {
			color: transparent;
			display: none;
			height: 0;
			max-height: 0;
			max-width: 0;
			opacity: 0;
			overflow: hidden;
			mso-hide: all;
			visibility: hidden;
			width: 0; 
			}
			.powered-by a {
			text-decoration: none; 
			}
			hr {
			border: 0;
			border-bottom: 1px solid #f6f6f6;
			margin: 20px 0; 
			}
    </style>
  </head>
  <body>
    <span class="preheader">This is preheader text. Some clients will show this text as a preview.</span>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
      <tr>
        <td>&nbsp;</td>
        <td class="container">
          <div class="content">

            <!-- START CENTERED WHITE CONTAINER -->
            <table role="presentation" class="main">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper">
                  <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                    <tr>
											<td class="header">
												<h1>
													<a href="/">LSBFGTMP</a>
												</h1>
												<p>Luleå Super Best Friends Game Tournament Mainframe Program</p>
											</td>
										</tr>
										<tr>
                      <td>
                        <p>{{ pre_buttons_message }}</p>
											</td>
										</tr>
{% if event %}
										<tr>
											<td>
												<table class="table table-striped" border="0" cellpadding="0" cellspacing="0">
													<tbody>
														<tr>
															<th align="center">Eventnamn</th>
															<td>{{ event.name }}</td>
														</tr>
														<tr>
															<th align="center">Anordnare</th>
															<td>{{ event.added_by }}</td>
														</tr>
														<tr>
															<th align="center">Tid</th>
															<td>{{ event.date }}{% if event.date_preliminary %} (Preliminärt) {% endif %}</td>
														</tr>
														<tr>
															<th align="center">Plats</th>
															<td>{{ event.location }}
																{% if event.location_href %}
																<a target="_blank" href="{{ event.location_href }}">(Länk)</a>
																{% endif %}
															</td>
														</tr>
														<tr>
															<th align="center">Typ</th>
															<td>{{ event.get_type_display  }}</td>
														</tr>
														<tr>
															<th align="center">Spel</th>
															<td>
																{% for game in event.games.all %}
																&bull;{{ game }}<br>
																{% endfor %}
																<p>Spel kan tillkomma eller försvinna!
																<p>
															</td>
														</tr>
												</table>
											</td>
										</tr>
{% endif %}

{% if buttons %}
	{% for link,text in buttons.items %}
										<tr>
											<td align="center">
												<a href="{{ link }}" class="btn2" target="_blank">{{ text }}</a>
											</td>
										</tr>
	{% endfor %}
{% endif %}

{% if post_buttons_message %}
										<tr>
											<td align="center">
												<p>{{ post_buttons_message }}</p>
											</td>
										</tr>
										
{% endif %}
                        <p>This is a really simple email template. Its sole purpose is to get the recipient to click the button with no distractions.</p>
                        <p>Good luck! Hope it works.</p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>
            <!-- END CENTERED WHITE CONTAINER -->

            <!-- START FOOTER -->
            <div class="footer">
              <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block">
                    <span class="apple-link">Company Inc, 3 Abbey Road, San Francisco CA 94102</span>
                    <br> Don't like these emails? <a href="http://i.imgur.com/CScmqnj.gif">Unsubscribe</a>.
                  </td>
                </tr>
                <tr>
                  <td class="content-block powered-by">
                    Powered by <a href="http://htmlemail.io">HTMLemail</a>.
                  </td>
                </tr>
              </table>
            </div>
            <!-- END FOOTER -->

          </div>
        </td>
        <td>&nbsp;</td>
      </tr>
    </table>
  </body>
</html>